disabled_rules:
    - identifier_name
    - function_body_length
opt_in_rules:
    - empty_count

excluded:
    - Carthage
    - Pods

line_length:
    - warning: 150
    - error: 200

cyclomatic_complexity:
  ignores_case_statements: true
