workflows:
  moviex-workflow:
    name: moviex_workflow
    scripts:
      - name: CI CD Started
        script: echo "Welcome"
    publishing:
      email:
        recipients:
          - dimascode012@gmail.com
