workflows:
  moviex-workflow: # workflow ID
    name: moviex_workflow # workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_PROJECT: "MovieX.xcworkspace"
          XCODE_SCHEME: "MovieX"
    scripts:
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: |
                    keychain initialize
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - dimacode012@gmail.com
