workflows:
  moviex-workflow: # workflow ID
    name: moviex_workflow # workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_WORKSPACE: "MovieX.xcworkspace"
          XCODE_SCHEME: "MovieX"
    scripts:
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: |
                    keychain initialize
      - name: Increment build number
        script: agvtool new-version -all $(($BUILD_NUMBER +1))
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - dimacode012@gmail.com
