workflows:
  moviex-workflow: # workflow ID
    name: moviex_workflow # workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_WORKSPACE: "MovieX.xcworkspace"
          XCODE_SCHEME: "MovieX"
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install --repo-update
      - name: Build the .app
        script: |
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 11,OS=16.1' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - dimacode012@gmail.com
